/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SourceReliability = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
  'NotSet' : IDL.Null,
});
export const PropagandaAnalysis = IDL.Record({
  'fear_based_language' : IDL.Bool,
  'selective_facts' : IDL.Bool,
  'emotional_manipulation' : IDL.Bool,
  'suggested_rewrite' : IDL.Opt(IDL.Text),
  'ideological_pushing' : IDL.Bool,
});
export const BiasIndicator = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const Classification = IDL.Variant({
  'Fact' : IDL.Null,
  'Opinion' : IDL.Null,
  'Unverified' : IDL.Null,
});
export const ArticleInput = IDL.Record({
  'source_reliability' : SourceReliability,
  'propaganda_analysis' : PropagandaAnalysis,
  'body' : IDL.Text,
  'headline' : IDL.Text,
  'fact_completeness_score' : IDL.Nat,
  'source_reliability_score' : IDL.Nat,
  'author' : IDL.Text,
  'summary' : IDL.Text,
  'no_contradiction_flag' : IDL.Nat,
  'category' : IDL.Text,
  'publication_date' : IDL.Int,
  'bias_indicator' : BiasIndicator,
  'source_outlet' : IDL.Text,
  'classification' : Classification,
});
export const ArticleId = IDL.Nat;
export const StreamStatus = IDL.Variant({
  'Ended' : IDL.Null,
  'Live' : IDL.Null,
  'Upcoming' : IDL.Null,
});
export const LiveStreamInput = IDL.Record({
  'status' : StreamStatus,
  'title' : IDL.Text,
  'source' : IDL.Text,
  'description' : IDL.Text,
  'start_time' : IDL.Int,
  'embed_url' : IDL.Text,
});
export const StreamId = IDL.Nat;
export const AdminResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const ContactResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const Article = IDL.Record({
  'id' : ArticleId,
  'source_reliability' : SourceReliability,
  'propaganda_analysis' : PropagandaAnalysis,
  'body' : IDL.Text,
  'published' : IDL.Bool,
  'headline' : IDL.Text,
  'fact_completeness_score' : IDL.Nat,
  'source_reliability_score' : IDL.Nat,
  'author' : IDL.Text,
  'summary' : IDL.Text,
  'no_contradiction_flag' : IDL.Nat,
  'category' : IDL.Text,
  'truth_score' : IDL.Nat,
  'publication_date' : IDL.Int,
  'bias_indicator' : BiasIndicator,
  'source_outlet' : IDL.Text,
  'classification' : Classification,
});
export const AuditLogEntry = IDL.Record({
  'id' : IDL.Nat,
  'resource_title' : IDL.Text,
  'action' : IDL.Text,
  'principal_text' : IDL.Text,
  'timestamp' : IDL.Int,
  'resource_id' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'isRead' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const DashboardStats = IDL.Record({
  'low_reliability_count' : IDL.Nat,
  'medium_reliability_count' : IDL.Nat,
  'last_updated' : IDL.Int,
  'propaganda_alert_count' : IDL.Nat,
  'low_bias_count' : IDL.Nat,
  'verified_count' : IDL.Nat,
  'unverified_count' : IDL.Nat,
  'high_bias_count' : IDL.Nat,
  'high_reliability_count' : IDL.Nat,
  'total_articles' : IDL.Nat,
  'medium_bias_count' : IDL.Nat,
  'opinion_count' : IDL.Nat,
});
export const NewsFetchStatus = IDL.Record({
  'lastFetchTime' : IDL.Int,
  'fetchedCount' : IDL.Nat,
});
export const LiveStream = IDL.Record({
  'id' : StreamId,
  'status' : StreamStatus,
  'title' : IDL.Text,
  'source' : IDL.Text,
  'published' : IDL.Bool,
  'description' : IDL.Text,
  'start_time' : IDL.Int,
  'embed_url' : IDL.Text,
});
export const NewsFetchResult = IDL.Variant({
  'ok' : IDL.Text,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'adminSubmitArticle' : IDL.Func(
      [ArticleInput],
      [IDL.Variant({ 'ok' : ArticleId, 'err' : IDL.Text })],
      [],
    ),
  'adminSubmitStream' : IDL.Func(
      [LiveStreamInput],
      [IDL.Variant({ 'ok' : StreamId, 'err' : IDL.Text })],
      [],
    ),
  'clearAuditLog' : IDL.Func([], [AdminResult], []),
  'deleteArticle' : IDL.Func(
      [ArticleId],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteContactSubmission' : IDL.Func([IDL.Nat], [ContactResult], []),
  'deleteStream' : IDL.Func(
      [StreamId],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'fetchAndImportNews' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getAdminPrincipalText' : IDL.Func([], [IDL.Text], ['query']),
  'getArticle' : IDL.Func([ArticleId], [IDL.Opt(Article)], ['query']),
  'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getAuditLog' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(AuditLogEntry)],
      ['query'],
    ),
  'getContactSubmissions' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getNewsApiKey' : IDL.Func([], [IDL.Text], ['query']),
  'getNewsFetchStatus' : IDL.Func([], [NewsFetchStatus], ['query']),
  'getPublishedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getPublishedStreams' : IDL.Func([], [IDL.Vec(LiveStream)], ['query']),
  'getStreams' : IDL.Func([], [IDL.Vec(LiveStream)], ['query']),
  'getUnreadContactCount' : IDL.Func([], [IDL.Nat], ['query']),
  'initAdmin' : IDL.Func([], [AdminResult], []),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markContactRead' : IDL.Func([IDL.Nat], [ContactResult], []),
  'setNewsApiKey' : IDL.Func([IDL.Text], [NewsFetchResult], []),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ContactResult],
      [],
    ),
  'toggleArticlePublished' : IDL.Func(
      [ArticleId],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'toggleStreamPublished' : IDL.Func(
      [StreamId],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'transferAdmin' : IDL.Func([IDL.Text], [AdminResult], []),
  'updateArticle' : IDL.Func(
      [ArticleId, ArticleInput],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'updateStream' : IDL.Func(
      [StreamId, LiveStreamInput],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SourceReliability = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
    'NotSet' : IDL.Null,
  });
  const PropagandaAnalysis = IDL.Record({
    'fear_based_language' : IDL.Bool,
    'selective_facts' : IDL.Bool,
    'emotional_manipulation' : IDL.Bool,
    'suggested_rewrite' : IDL.Opt(IDL.Text),
    'ideological_pushing' : IDL.Bool,
  });
  const BiasIndicator = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const Classification = IDL.Variant({
    'Fact' : IDL.Null,
    'Opinion' : IDL.Null,
    'Unverified' : IDL.Null,
  });
  const ArticleInput = IDL.Record({
    'source_reliability' : SourceReliability,
    'propaganda_analysis' : PropagandaAnalysis,
    'body' : IDL.Text,
    'headline' : IDL.Text,
    'fact_completeness_score' : IDL.Nat,
    'source_reliability_score' : IDL.Nat,
    'author' : IDL.Text,
    'summary' : IDL.Text,
    'no_contradiction_flag' : IDL.Nat,
    'category' : IDL.Text,
    'publication_date' : IDL.Int,
    'bias_indicator' : BiasIndicator,
    'source_outlet' : IDL.Text,
    'classification' : Classification,
  });
  const ArticleId = IDL.Nat;
  const StreamStatus = IDL.Variant({
    'Ended' : IDL.Null,
    'Live' : IDL.Null,
    'Upcoming' : IDL.Null,
  });
  const LiveStreamInput = IDL.Record({
    'status' : StreamStatus,
    'title' : IDL.Text,
    'source' : IDL.Text,
    'description' : IDL.Text,
    'start_time' : IDL.Int,
    'embed_url' : IDL.Text,
  });
  const StreamId = IDL.Nat;
  const AdminResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const ContactResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const Article = IDL.Record({
    'id' : ArticleId,
    'source_reliability' : SourceReliability,
    'propaganda_analysis' : PropagandaAnalysis,
    'body' : IDL.Text,
    'published' : IDL.Bool,
    'headline' : IDL.Text,
    'fact_completeness_score' : IDL.Nat,
    'source_reliability_score' : IDL.Nat,
    'author' : IDL.Text,
    'summary' : IDL.Text,
    'no_contradiction_flag' : IDL.Nat,
    'category' : IDL.Text,
    'truth_score' : IDL.Nat,
    'publication_date' : IDL.Int,
    'bias_indicator' : BiasIndicator,
    'source_outlet' : IDL.Text,
    'classification' : Classification,
  });
  const AuditLogEntry = IDL.Record({
    'id' : IDL.Nat,
    'resource_title' : IDL.Text,
    'action' : IDL.Text,
    'principal_text' : IDL.Text,
    'timestamp' : IDL.Int,
    'resource_id' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'isRead' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const DashboardStats = IDL.Record({
    'low_reliability_count' : IDL.Nat,
    'medium_reliability_count' : IDL.Nat,
    'last_updated' : IDL.Int,
    'propaganda_alert_count' : IDL.Nat,
    'low_bias_count' : IDL.Nat,
    'verified_count' : IDL.Nat,
    'unverified_count' : IDL.Nat,
    'high_bias_count' : IDL.Nat,
    'high_reliability_count' : IDL.Nat,
    'total_articles' : IDL.Nat,
    'medium_bias_count' : IDL.Nat,
    'opinion_count' : IDL.Nat,
  });
  const NewsFetchStatus = IDL.Record({
    'lastFetchTime' : IDL.Int,
    'fetchedCount' : IDL.Nat,
  });
  const LiveStream = IDL.Record({
    'id' : StreamId,
    'status' : StreamStatus,
    'title' : IDL.Text,
    'source' : IDL.Text,
    'published' : IDL.Bool,
    'description' : IDL.Text,
    'start_time' : IDL.Int,
    'embed_url' : IDL.Text,
  });
  const NewsFetchResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  
  return IDL.Service({
    'adminSubmitArticle' : IDL.Func(
        [ArticleInput],
        [IDL.Variant({ 'ok' : ArticleId, 'err' : IDL.Text })],
        [],
      ),
    'adminSubmitStream' : IDL.Func(
        [LiveStreamInput],
        [IDL.Variant({ 'ok' : StreamId, 'err' : IDL.Text })],
        [],
      ),
    'clearAuditLog' : IDL.Func([], [AdminResult], []),
    'deleteArticle' : IDL.Func(
        [ArticleId],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteContactSubmission' : IDL.Func([IDL.Nat], [ContactResult], []),
    'deleteStream' : IDL.Func(
        [StreamId],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'fetchAndImportNews' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getAdminPrincipalText' : IDL.Func([], [IDL.Text], ['query']),
    'getArticle' : IDL.Func([ArticleId], [IDL.Opt(Article)], ['query']),
    'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getAuditLog' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(AuditLogEntry)],
        ['query'],
      ),
    'getContactSubmissions' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getNewsApiKey' : IDL.Func([], [IDL.Text], ['query']),
    'getNewsFetchStatus' : IDL.Func([], [NewsFetchStatus], ['query']),
    'getPublishedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getPublishedStreams' : IDL.Func([], [IDL.Vec(LiveStream)], ['query']),
    'getStreams' : IDL.Func([], [IDL.Vec(LiveStream)], ['query']),
    'getUnreadContactCount' : IDL.Func([], [IDL.Nat], ['query']),
    'initAdmin' : IDL.Func([], [AdminResult], []),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markContactRead' : IDL.Func([IDL.Nat], [ContactResult], []),
    'setNewsApiKey' : IDL.Func([IDL.Text], [NewsFetchResult], []),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ContactResult],
        [],
      ),
    'toggleArticlePublished' : IDL.Func(
        [ArticleId],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'toggleStreamPublished' : IDL.Func(
        [StreamId],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'transferAdmin' : IDL.Func([IDL.Text], [AdminResult], []),
    'updateArticle' : IDL.Func(
        [ArticleId, ArticleInput],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'updateStream' : IDL.Func(
        [StreamId, LiveStreamInput],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };