/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdminResult = { 'ok' : string } |
  { 'err' : string };
export interface Article {
  'id' : ArticleId,
  'source_reliability' : SourceReliability,
  'propaganda_analysis' : PropagandaAnalysis,
  'body' : string,
  'published' : boolean,
  'headline' : string,
  'fact_completeness_score' : bigint,
  'source_reliability_score' : bigint,
  'author' : string,
  'summary' : string,
  'no_contradiction_flag' : bigint,
  'category' : string,
  'truth_score' : bigint,
  'publication_date' : bigint,
  'bias_indicator' : BiasIndicator,
  'source_outlet' : string,
  'classification' : Classification,
}
export type ArticleId = bigint;
export interface ArticleInput {
  'source_reliability' : SourceReliability,
  'propaganda_analysis' : PropagandaAnalysis,
  'body' : string,
  'headline' : string,
  'fact_completeness_score' : bigint,
  'source_reliability_score' : bigint,
  'author' : string,
  'summary' : string,
  'no_contradiction_flag' : bigint,
  'category' : string,
  'publication_date' : bigint,
  'bias_indicator' : BiasIndicator,
  'source_outlet' : string,
  'classification' : Classification,
}
export interface AuditLogEntry {
  'id' : bigint,
  'resource_title' : string,
  'action' : string,
  'principal_text' : string,
  'timestamp' : bigint,
  'resource_id' : string,
}
export type BiasIndicator = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export type Classification = { 'Fact' : null } |
  { 'Opinion' : null } |
  { 'Unverified' : null };
export type ContactResult = { 'ok' : string } |
  { 'err' : string };
export interface ContactSubmission {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'isRead' : boolean,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface DashboardStats {
  'low_reliability_count' : bigint,
  'medium_reliability_count' : bigint,
  'last_updated' : bigint,
  'propaganda_alert_count' : bigint,
  'low_bias_count' : bigint,
  'verified_count' : bigint,
  'unverified_count' : bigint,
  'high_bias_count' : bigint,
  'high_reliability_count' : bigint,
  'total_articles' : bigint,
  'medium_bias_count' : bigint,
  'opinion_count' : bigint,
}
export interface LiveStream {
  'id' : StreamId,
  'status' : StreamStatus,
  'title' : string,
  'source' : string,
  'published' : boolean,
  'description' : string,
  'start_time' : bigint,
  'embed_url' : string,
}
export interface LiveStreamInput {
  'status' : StreamStatus,
  'title' : string,
  'source' : string,
  'description' : string,
  'start_time' : bigint,
  'embed_url' : string,
}
export type NewsFetchResult = { 'ok' : string } |
  { 'err' : string };
export interface NewsFetchStatus {
  'lastFetchTime' : bigint,
  'fetchedCount' : bigint,
}
export interface PropagandaAnalysis {
  'fear_based_language' : boolean,
  'selective_facts' : boolean,
  'emotional_manipulation' : boolean,
  'suggested_rewrite' : [] | [string],
  'ideological_pushing' : boolean,
}
export type SourceReliability = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null } |
  { 'NotSet' : null };
export type StreamId = bigint;
export type StreamStatus = { 'Ended' : null } |
  { 'Live' : null } |
  { 'Upcoming' : null };
export interface _SERVICE {
  'adminSubmitArticle' : ActorMethod<
    [ArticleInput],
    { 'ok' : ArticleId } |
      { 'err' : string }
  >,
  'adminSubmitStream' : ActorMethod<
    [LiveStreamInput],
    { 'ok' : StreamId } |
      { 'err' : string }
  >,
  'clearAuditLog' : ActorMethod<[], AdminResult>,
  'deleteArticle' : ActorMethod<
    [ArticleId],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteContactSubmission' : ActorMethod<[bigint], ContactResult>,
  'deleteStream' : ActorMethod<
    [StreamId],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'fetchAndImportNews' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getAdminPrincipalText' : ActorMethod<[], string>,
  'getArticle' : ActorMethod<[ArticleId], [] | [Article]>,
  'getArticles' : ActorMethod<[], Array<Article>>,
  'getAuditLog' : ActorMethod<[bigint, bigint], Array<AuditLogEntry>>,
  'getContactSubmissions' : ActorMethod<
    [bigint, bigint],
    Array<ContactSubmission>
  >,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getNewsApiKey' : ActorMethod<[], string>,
  'getNewsFetchStatus' : ActorMethod<[], NewsFetchStatus>,
  'getPublishedArticles' : ActorMethod<[], Array<Article>>,
  'getPublishedStreams' : ActorMethod<[], Array<LiveStream>>,
  'getStreams' : ActorMethod<[], Array<LiveStream>>,
  'getUnreadContactCount' : ActorMethod<[], bigint>,
  'initAdmin' : ActorMethod<[], AdminResult>,
  'isAdmin' : ActorMethod<[], boolean>,
  'markContactRead' : ActorMethod<[bigint], ContactResult>,
  'setNewsApiKey' : ActorMethod<[string], NewsFetchResult>,
  'submitContact' : ActorMethod<
    [string, string, string, string],
    ContactResult
  >,
  'toggleArticlePublished' : ActorMethod<
    [ArticleId],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'toggleStreamPublished' : ActorMethod<
    [StreamId],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'transferAdmin' : ActorMethod<[string], AdminResult>,
  'updateArticle' : ActorMethod<
    [ArticleId, ArticleInput],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateStream' : ActorMethod<
    [StreamId, LiveStreamInput],
    { 'ok' : string } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];