/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type NewsFetchResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface Article {
    id: ArticleId;
    source_reliability: SourceReliability;
    propaganda_analysis: PropagandaAnalysis;
    body: string;
    published: boolean;
    headline: string;
    fact_completeness_score: bigint;
    source_reliability_score: bigint;
    author: string;
    summary: string;
    no_contradiction_flag: bigint;
    category: string;
    truth_score: bigint;
    publication_date: bigint;
    bias_indicator: BiasIndicator;
    source_outlet: string;
    classification: Classification;
}
export type AdminResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface ContactSubmission {
    id: bigint;
    subject: string;
    name: string;
    isRead: boolean;
    email: string;
    message: string;
    timestamp: bigint;
}
export interface AuditLogEntry {
    id: bigint;
    resource_title: string;
    action: string;
    principal_text: string;
    timestamp: bigint;
    resource_id: string;
}
export type ArticleId = bigint;
export interface DashboardStats {
    low_reliability_count: bigint;
    medium_reliability_count: bigint;
    last_updated: bigint;
    propaganda_alert_count: bigint;
    low_bias_count: bigint;
    verified_count: bigint;
    unverified_count: bigint;
    high_bias_count: bigint;
    high_reliability_count: bigint;
    total_articles: bigint;
    medium_bias_count: bigint;
    opinion_count: bigint;
}
export interface LiveStreamInput {
    status: StreamStatus;
    title: string;
    source: string;
    description: string;
    start_time: bigint;
    embed_url: string;
}
export interface PropagandaAnalysis {
    fear_based_language: boolean;
    selective_facts: boolean;
    emotional_manipulation: boolean;
    suggested_rewrite?: string;
    ideological_pushing: boolean;
}
export interface ArticleInput {
    source_reliability: SourceReliability;
    propaganda_analysis: PropagandaAnalysis;
    body: string;
    headline: string;
    fact_completeness_score: bigint;
    source_reliability_score: bigint;
    author: string;
    summary: string;
    no_contradiction_flag: bigint;
    category: string;
    publication_date: bigint;
    bias_indicator: BiasIndicator;
    source_outlet: string;
    classification: Classification;
}
export type ContactResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export type StreamId = bigint;
export interface LiveStream {
    id: StreamId;
    status: StreamStatus;
    title: string;
    source: string;
    published: boolean;
    description: string;
    start_time: bigint;
    embed_url: string;
}
export interface NewsFetchStatus {
    lastFetchTime: bigint;
    fetchedCount: bigint;
}
export enum BiasIndicator {
    Low = "Low",
    High = "High",
    Medium = "Medium"
}
export enum Classification {
    Fact = "Fact",
    Opinion = "Opinion",
    Unverified = "Unverified"
}
export enum SourceReliability {
    Low = "Low",
    High = "High",
    Medium = "Medium",
    NotSet = "NotSet"
}
export enum StreamStatus {
    Ended = "Ended",
    Live = "Live",
    Upcoming = "Upcoming"
}
export interface backendInterface {
    adminSubmitArticle(input: ArticleInput): Promise<{
        __kind__: "ok";
        ok: ArticleId;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminSubmitStream(input: LiveStreamInput): Promise<{
        __kind__: "ok";
        ok: StreamId;
    } | {
        __kind__: "err";
        err: string;
    }>;
    clearAuditLog(): Promise<AdminResult>;
    deleteArticle(id: ArticleId): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteContactSubmission(id: bigint): Promise<ContactResult>;
    deleteStream(id: StreamId): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    fetchAndImportNews(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAdminPrincipalText(): Promise<string>;
    getArticle(id: ArticleId): Promise<Article | null>;
    getArticles(): Promise<Array<Article>>;
    getAuditLog(offset: bigint, limit: bigint): Promise<Array<AuditLogEntry>>;
    getContactSubmissions(offset: bigint, limit: bigint): Promise<Array<ContactSubmission>>;
    getDashboardStats(): Promise<DashboardStats>;
    getNewsApiKey(): Promise<string>;
    getNewsFetchStatus(): Promise<NewsFetchStatus>;
    getPublishedArticles(): Promise<Array<Article>>;
    getPublishedStreams(): Promise<Array<LiveStream>>;
    getStreams(): Promise<Array<LiveStream>>;
    getUnreadContactCount(): Promise<bigint>;
    initAdmin(): Promise<AdminResult>;
    isAdmin(): Promise<boolean>;
    markContactRead(id: bigint): Promise<ContactResult>;
    setNewsApiKey(key: string): Promise<NewsFetchResult>;
    submitContact(name: string, email: string, subject: string, message: string): Promise<ContactResult>;
    toggleArticlePublished(id: ArticleId): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    toggleStreamPublished(id: StreamId): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    transferAdmin(newPrincipalText: string): Promise<AdminResult>;
    updateArticle(id: ArticleId, input: ArticleInput): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateStream(id: StreamId, input: LiveStreamInput): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { AdminResult as _AdminResult, Article as _Article, ArticleId as _ArticleId, ArticleInput as _ArticleInput, BiasIndicator as _BiasIndicator, Classification as _Classification, ContactResult as _ContactResult, LiveStream as _LiveStream, LiveStreamInput as _LiveStreamInput, NewsFetchResult as _NewsFetchResult, PropagandaAnalysis as _PropagandaAnalysis, SourceReliability as _SourceReliability, StreamId as _StreamId, StreamStatus as _StreamStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminSubmitArticle(arg0: ArticleInput): Promise<{
        __kind__: "ok";
        ok: ArticleId;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSubmitArticle(to_candid_ArticleInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSubmitArticle(to_candid_ArticleInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminSubmitStream(arg0: LiveStreamInput): Promise<{
        __kind__: "ok";
        ok: StreamId;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSubmitStream(to_candid_LiveStreamInput_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSubmitStream(to_candid_LiveStreamInput_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearAuditLog(): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAuditLog();
                return from_candid_AdminResult_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAuditLog();
            return from_candid_AdminResult_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteArticle(arg0: ArticleId): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteArticle(arg0);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteArticle(arg0);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteContactSubmission(arg0: bigint): Promise<ContactResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContactSubmission(arg0);
                return from_candid_ContactResult_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContactSubmission(arg0);
            return from_candid_ContactResult_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteStream(arg0: StreamId): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStream(arg0);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStream(arg0);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchAndImportNews(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchAndImportNews();
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchAndImportNews();
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminPrincipalText(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPrincipalText();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPrincipalText();
            return result;
        }
    }
    async getArticle(arg0: ArticleId): Promise<Article | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticle(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticle(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticles();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticles();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditLog(arg0: bigint, arg1: bigint): Promise<Array<AuditLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLog(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLog(arg0, arg1);
            return result;
        }
    }
    async getContactSubmissions(arg0: bigint, arg1: bigint): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSubmissions(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSubmissions(arg0, arg1);
            return result;
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getNewsApiKey(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsApiKey();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsApiKey();
            return result;
        }
    }
    async getNewsFetchStatus(): Promise<NewsFetchStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsFetchStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsFetchStatus();
            return result;
        }
    }
    async getPublishedArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedArticles();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedArticles();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedStreams(): Promise<Array<LiveStream>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedStreams();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedStreams();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStreams(): Promise<Array<LiveStream>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStreams();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStreams();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadContactCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadContactCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadContactCount();
            return result;
        }
    }
    async initAdmin(): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.initAdmin();
                return from_candid_AdminResult_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initAdmin();
            return from_candid_AdminResult_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async markContactRead(arg0: bigint): Promise<ContactResult> {
        if (this.processError) {
            try {
                const result = await this.actor.markContactRead(arg0);
                return from_candid_ContactResult_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markContactRead(arg0);
            return from_candid_ContactResult_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async setNewsApiKey(arg0: string): Promise<NewsFetchResult> {
        if (this.processError) {
            try {
                const result = await this.actor.setNewsApiKey(arg0);
                return from_candid_NewsFetchResult_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setNewsApiKey(arg0);
            return from_candid_NewsFetchResult_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContact(arg0: string, arg1: string, arg2: string, arg3: string): Promise<ContactResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0, arg1, arg2, arg3);
                return from_candid_ContactResult_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0, arg1, arg2, arg3);
            return from_candid_ContactResult_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleArticlePublished(arg0: ArticleId): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleArticlePublished(arg0);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleArticlePublished(arg0);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleStreamPublished(arg0: StreamId): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleStreamPublished(arg0);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleStreamPublished(arg0);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async transferAdmin(arg0: string): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.transferAdmin(arg0);
                return from_candid_AdminResult_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferAdmin(arg0);
            return from_candid_AdminResult_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateArticle(arg0: ArticleId, arg1: ArticleInput): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArticle(arg0, to_candid_ArticleInput_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArticle(arg0, to_candid_ArticleInput_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateStream(arg0: StreamId, arg1: LiveStreamInput): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStream(arg0, to_candid_LiveStreamInput_n12(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStream(arg0, to_candid_LiveStreamInput_n12(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AdminResult_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminResult): AdminResult {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Article_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Article): Article {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_BiasIndicator_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BiasIndicator): BiasIndicator {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Classification_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Classification): Classification {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_ContactResult_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactResult): ContactResult {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_LiveStream_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LiveStream): LiveStream {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_NewsFetchResult_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsFetchResult): NewsFetchResult {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_PropagandaAnalysis_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropagandaAnalysis): PropagandaAnalysis {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_SourceReliability_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SourceReliability): SourceReliability {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_StreamStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StreamStatus): StreamStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Article]): Article | null {
    return value.length === 0 ? null : from_candid_Article_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ArticleId;
    source_reliability: _SourceReliability;
    propaganda_analysis: _PropagandaAnalysis;
    body: string;
    published: boolean;
    headline: string;
    fact_completeness_score: bigint;
    source_reliability_score: bigint;
    author: string;
    summary: string;
    no_contradiction_flag: bigint;
    category: string;
    truth_score: bigint;
    publication_date: bigint;
    bias_indicator: _BiasIndicator;
    source_outlet: string;
    classification: _Classification;
}): {
    id: ArticleId;
    source_reliability: SourceReliability;
    propaganda_analysis: PropagandaAnalysis;
    body: string;
    published: boolean;
    headline: string;
    fact_completeness_score: bigint;
    source_reliability_score: bigint;
    author: string;
    summary: string;
    no_contradiction_flag: bigint;
    category: string;
    truth_score: bigint;
    publication_date: bigint;
    bias_indicator: BiasIndicator;
    source_outlet: string;
    classification: Classification;
} {
    return {
        id: value.id,
        source_reliability: from_candid_SourceReliability_n23(_uploadFile, _downloadFile, value.source_reliability),
        propaganda_analysis: from_candid_PropagandaAnalysis_n25(_uploadFile, _downloadFile, value.propaganda_analysis),
        body: value.body,
        published: value.published,
        headline: value.headline,
        fact_completeness_score: value.fact_completeness_score,
        source_reliability_score: value.source_reliability_score,
        author: value.author,
        summary: value.summary,
        no_contradiction_flag: value.no_contradiction_flag,
        category: value.category,
        truth_score: value.truth_score,
        publication_date: value.publication_date,
        bias_indicator: from_candid_BiasIndicator_n28(_uploadFile, _downloadFile, value.bias_indicator),
        source_outlet: value.source_outlet,
        classification: from_candid_Classification_n30(_uploadFile, _downloadFile, value.classification)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fear_based_language: boolean;
    selective_facts: boolean;
    emotional_manipulation: boolean;
    suggested_rewrite: [] | [string];
    ideological_pushing: boolean;
}): {
    fear_based_language: boolean;
    selective_facts: boolean;
    emotional_manipulation: boolean;
    suggested_rewrite?: string;
    ideological_pushing: boolean;
} {
    return {
        fear_based_language: value.fear_based_language,
        selective_facts: value.selective_facts,
        emotional_manipulation: value.emotional_manipulation,
        suggested_rewrite: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.suggested_rewrite)),
        ideological_pushing: value.ideological_pushing
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StreamId;
    status: _StreamStatus;
    title: string;
    source: string;
    published: boolean;
    description: string;
    start_time: bigint;
    embed_url: string;
}): {
    id: StreamId;
    status: StreamStatus;
    title: string;
    source: string;
    published: boolean;
    description: string;
    start_time: bigint;
    embed_url: string;
} {
    return {
        id: value.id,
        status: from_candid_StreamStatus_n36(_uploadFile, _downloadFile, value.status),
        title: value.title,
        source: value.source,
        published: value.published,
        description: value.description,
        start_time: value.start_time,
        embed_url: value.embed_url
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ArticleId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ArticleId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _StreamId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: StreamId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} | {
    NotSet: null;
}): SourceReliability {
    return "Low" in value ? SourceReliability.Low : "High" in value ? SourceReliability.High : "Medium" in value ? SourceReliability.Medium : "NotSet" in value ? SourceReliability.NotSet : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
}): BiasIndicator {
    return "Low" in value ? BiasIndicator.Low : "High" in value ? BiasIndicator.High : "Medium" in value ? BiasIndicator.Medium : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Fact: null;
} | {
    Opinion: null;
} | {
    Unverified: null;
}): Classification {
    return "Fact" in value ? Classification.Fact : "Opinion" in value ? Classification.Opinion : "Unverified" in value ? Classification.Unverified : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Ended: null;
} | {
    Live: null;
} | {
    Upcoming: null;
}): StreamStatus {
    return "Ended" in value ? StreamStatus.Ended : "Live" in value ? StreamStatus.Live : "Upcoming" in value ? StreamStatus.Upcoming : value;
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Article>): Array<Article> {
    return value.map((x)=>from_candid_Article_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LiveStream>): Array<LiveStream> {
    return value.map((x)=>from_candid_LiveStream_n34(_uploadFile, _downloadFile, x));
}
function to_candid_ArticleInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArticleInput): _ArticleInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_BiasIndicator_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BiasIndicator): _BiasIndicator {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Classification_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Classification): _Classification {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_LiveStreamInput_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LiveStreamInput): _LiveStreamInput {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_PropagandaAnalysis_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropagandaAnalysis): _PropagandaAnalysis {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_SourceReliability_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SourceReliability): _SourceReliability {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_StreamStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StreamStatus): _StreamStatus {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: StreamStatus;
    title: string;
    source: string;
    description: string;
    start_time: bigint;
    embed_url: string;
}): {
    status: _StreamStatus;
    title: string;
    source: string;
    description: string;
    start_time: bigint;
    embed_url: string;
} {
    return {
        status: to_candid_StreamStatus_n14(_uploadFile, _downloadFile, value.status),
        title: value.title,
        source: value.source,
        description: value.description,
        start_time: value.start_time,
        embed_url: value.embed_url
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    source_reliability: SourceReliability;
    propaganda_analysis: PropagandaAnalysis;
    body: string;
    headline: string;
    fact_completeness_score: bigint;
    source_reliability_score: bigint;
    author: string;
    summary: string;
    no_contradiction_flag: bigint;
    category: string;
    publication_date: bigint;
    bias_indicator: BiasIndicator;
    source_outlet: string;
    classification: Classification;
}): {
    source_reliability: _SourceReliability;
    propaganda_analysis: _PropagandaAnalysis;
    body: string;
    headline: string;
    fact_completeness_score: bigint;
    source_reliability_score: bigint;
    author: string;
    summary: string;
    no_contradiction_flag: bigint;
    category: string;
    publication_date: bigint;
    bias_indicator: _BiasIndicator;
    source_outlet: string;
    classification: _Classification;
} {
    return {
        source_reliability: to_candid_SourceReliability_n3(_uploadFile, _downloadFile, value.source_reliability),
        propaganda_analysis: to_candid_PropagandaAnalysis_n5(_uploadFile, _downloadFile, value.propaganda_analysis),
        body: value.body,
        headline: value.headline,
        fact_completeness_score: value.fact_completeness_score,
        source_reliability_score: value.source_reliability_score,
        author: value.author,
        summary: value.summary,
        no_contradiction_flag: value.no_contradiction_flag,
        category: value.category,
        publication_date: value.publication_date,
        bias_indicator: to_candid_BiasIndicator_n7(_uploadFile, _downloadFile, value.bias_indicator),
        source_outlet: value.source_outlet,
        classification: to_candid_Classification_n9(_uploadFile, _downloadFile, value.classification)
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fear_based_language: boolean;
    selective_facts: boolean;
    emotional_manipulation: boolean;
    suggested_rewrite?: string;
    ideological_pushing: boolean;
}): {
    fear_based_language: boolean;
    selective_facts: boolean;
    emotional_manipulation: boolean;
    suggested_rewrite: [] | [string];
    ideological_pushing: boolean;
} {
    return {
        fear_based_language: value.fear_based_language,
        selective_facts: value.selective_facts,
        emotional_manipulation: value.emotional_manipulation,
        suggested_rewrite: value.suggested_rewrite ? candid_some(value.suggested_rewrite) : candid_none(),
        ideological_pushing: value.ideological_pushing
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Classification): {
    Fact: null;
} | {
    Opinion: null;
} | {
    Unverified: null;
} {
    return value == Classification.Fact ? {
        Fact: null
    } : value == Classification.Opinion ? {
        Opinion: null
    } : value == Classification.Unverified ? {
        Unverified: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StreamStatus): {
    Ended: null;
} | {
    Live: null;
} | {
    Upcoming: null;
} {
    return value == StreamStatus.Ended ? {
        Ended: null
    } : value == StreamStatus.Live ? {
        Live: null
    } : value == StreamStatus.Upcoming ? {
        Upcoming: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SourceReliability): {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} | {
    NotSet: null;
} {
    return value == SourceReliability.Low ? {
        Low: null
    } : value == SourceReliability.High ? {
        High: null
    } : value == SourceReliability.Medium ? {
        Medium: null
    } : value == SourceReliability.NotSet ? {
        NotSet: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BiasIndicator): {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} {
    return value == BiasIndicator.Low ? {
        Low: null
    } : value == BiasIndicator.High ? {
        High: null
    } : value == BiasIndicator.Medium ? {
        Medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
